### ISSUE TITLE
Channel tags are not saved

### ISSUE THREAD

**Issue by vadi2** [RhysSullivan/AnswerOverflowTracking#11]
Setting channel tags, clicking save, and changing the channels back and forth is not preserving the tags.

**Comment by RhysSullivan** [comment]
I tried to recreate this and wasn't able to, just to confirm you're adding a tag by:

1. Typing the tag into the input box
2. Hitting Enter
3. Clicking save
4. Having a confirmation in the top right saying 'Changes saved'

I tested adding tags to channels on your server and that worked on my end so I'm a bit confused on what may be causing what you're experiencing - if you could try adding the tags you want again and let me know if it works I'd appreciate that thank you.

Two notes are:
-Tags aren't applied if you don't click save
-The site doesn't notify you if you have unsaved changes although it probably should

**Comment by vadi2** [comment]
Got it - had to press Enter.

**Comment by RhysSullivan** [comment]
UX could be improved to make the process clearer, new issue created to improve that: https://github.com/RhysSullivan/AnswerOverflowTracking/issues/13
